### ISSUE TITLE
Adding nTPL to npm (node package manager)

### ISSUE THREAD

**Issue by mape** [indutny/nTPL#1]
Would it be possible for you to add nTPL to http://github.com/isaacs/npm making it easier to try out / install?

**Comment by indutny** [comment]
I'm working on this now.
Will reply here when all work will be done!

**Comment by mape** [comment]
Looking forward to it!

**Comment by indutny** [comment]
try this:
<code>npm install nTPL</code>

**Comment by indutny** [comment]
Can you confirm that it's working?

**Comment by mape** [comment]
The install seems to work fine, but when I run example.js i get a black box with rounded corners containing Hello, %username!!!

Is that the expected result?

**Comment by indutny** [comment]
Haha! Yeah! )
There is folder "tpl" in nTPL package, here you can see _base.html_ and _index.html_ files.
Try to change them, when server is running!

**Comment by indutny** [comment]
Also may me admit you to watch this repository!
You will be notified if I change something in demos or added new version
Believe me - that's cool! ;)

**Comment by mape** [comment]
Seems to work nice, now I just have to get it working in http://github.com/visionmedia/express and I'll be a happy man.

Thanks for the great work!

**Comment by indutny** [comment]
Thank you for using this!
