### ISSUE TITLE
Lowercase nTPL to ntpl

### ISSUE THREAD

**Issue by litemotiv** [indutny/nTPL#4]
Would it be possible to use a lowercase naming for ntpl instead of nTPL? I'm starting out with express and i'm finding that i need to name my template files foo.nTPL for auto detection. Setting an extra app.register for .ntpl is possible, but is extra config and requires the full template name to be called -- res.render('foo.ntpl') instead of res.render('foo').

**Comment by indutny** [comment]
Ok, I've pushed this to master. And later, today, I'll push it to npm

**Comment by litemotiv** [comment]
Excellent, thanks.
