### ISSUE TITLE
npm install nTPL fails due to error in package.json

### ISSUE THREAD

**Issue by nherment** [indutny/nTPL#6]
Here is the error:
`nherment-mac:modeln nherment$ npm install nTPL@0.4.6
npm ERR! couldn't unpack /var/folders/Rq/RqT8Xk4wHU8BoFW7GAhlc++++TI/-Tmp-/npm-1324461925521/1324461925521-0.5146478521637619/tmp.tgz to /var/folders/Rq/RqT8Xk4wHU8BoFW7GAhlc++++TI/-Tmp-/npm-1324461925521/1324461925521-0.5146478521637619
npm ERR! Failed to parse json
npm ERR! Unexpected token n
npm ERR! File: /var/folders/Rq/RqT8Xk4wHU8BoFW7GAhlc++++TI/-Tmp-/npm-1324461925521/1324461925521-0.5146478521637619/package/package.json
npm ERR! JSON.parse Failed to parse package.json data.
npm ERR! JSON.parse package.json must be actual JSON, not just JavaScript.
npm ERR! JSON.parse 
npm ERR! JSON.parse This is not a bug in npm.
npm ERR! JSON.parse Tell the package author to fix their package.json file.
npm ERR! 
npm ERR! System Darwin 10.8.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "nTPL"
npm ERR! cwd /Users/nherment/modeln/rms-modules/bin/modeln
npm ERR! node -v v0.6.3
npm ERR! npm -v 1.1.0-alpha-2
npm ERR! file /var/folders/Rq/RqT8Xk4wHU8BoFW7GAhlc++++TI/-Tmp-/npm-1324461925521/1324461925521-0.5146478521637619/package/package.json
npm ERR! code EJSONPARSE
npm ERR! message Failed to parse json
npm ERR! message Unexpected token n
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/nherment/modeln/rms-modules/bin/modeln/npm-debug.log
npm not ok`

It is due to the 'contributor' section of the package.json which is not valid Json:
`
        {
            name: "Fedor Indutny",
            email: "fedor.indutny@gmail.com"
        }
`
name and email are missing quotes.

**Comment by indutny** [comment]
hi!

I'm glad that you're interested, but this project is quite **unsupported**.
Sorry, native js templates are fast now and there're no need in C++ based template generation, so I left maintaining this project.

But you should I take a look at [jade](https://github.com/visionmedia/jade) or [ejs](https://github.com/visionmedia/ejs) if you're searching for a good node.js template engine.

Thanks

**Comment by nherment** [comment]
Haha ! already looked at those and chose to use yours :)
Jade doesn't fit the bill but ejs will do :)
Thanks !
